### ISSUE TITLE
tensorflow dependency overrides a preexisting GPU installation

### ISSUE THREAD

**Issue by snormore** [triagemd/ml-tools#13]
Do we need `ml-tools-gpu` that depends on `tensorflow-gpu` instead?

**Comment by stephensolis** [comment]
The tensorflow dependency is only needed for the model conversion code. Considering the coreml converter will require Python 2.7 (only), how about splitting model converters into their own package and document that it will break tensorflow-gpu?

**Comment by snormore** [comment]
Yea I like the idea of splitting it out for that reason and because it's adding significant overhead to test/CI runs for this repo already.

**Comment by stephensolis** [comment]
I ended up going with `model-converters` just in case we ever add other ones (say Tensorflow -> CoreML, etc.)

https://github.com/triagemd/model-converters

**Comment by stephensolis** [comment]
https://pypi.python.org/pypi/model-converters
