### ISSUE TITLE
Update your `Model` call to the Keras 2 API

### ISSUE THREAD

**Issue by iamrosmarin** [triagemd/ml-tools#17]
Hi guys,

I’m receiving this warning message while using the [`parallel.py`](https://github.com/triagemd/ml-tools/blob/master/ml_tools/parallel.py) script: 

```/home/snormore/venvs/keras/lib/python2.7/site-packages/ml_tools/parallel.py:72: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[<tf.Tenso..., inputs=[<tf.Tenso...)`
  return Model(input=model.inputs, output=merged)``` 

Hope you can help me to figure out why it's happening!

Thanks.

**Comment by MohMehrnia** [comment]
set this syntax Model(inputs=model.inputs, outputs=merged)
